.set-remote-github:
  script:
    - git remote add $CI_COMMIT_REF_NAME https://aenima-x:${GH_TOKEN2}@github.com/aenima-x/faraday.git
  allow_failure: true

update_github:
    image: python:3
    stage: publish
    script:
      - !reference [.set-remote-github, script]
      - !reference [ .get_from_tar_and_replace_www, script ]
      - git add .
      - git config --global user.email "devops@faradaysec.com"
      - git config --global user.name "Devops"
      - git commit -m "Front Updated"
      #- git show-ref
      - git push --force $CI_COMMIT_REF_NAME $CI_COMMIT_REF_NAME:master
    rules:
      - if: $FORK_TEST
      - if: '$CI_COMMIT_REF_NAME == "white/master"'
        variables:
          DESTINY_BRANCH: master
        when: on_success
#      - if: '$CI_COMMIT_REF_NAME == "white/staging"'
#        variables:
#          DESTINY_BRANCH: staging
#        when: on_success
    needs:
      - project: faradaysec/faraday-react
        job: npm_build
        ref: community/dev
        artifacts: true


tag_on_github:
    image: python:3
    stage: publish
    script:
      - !reference [.set-remote-github, script]
      - export FARADAY_VERSION=$(eval $IMAGE_TAG)
      - CHANGELOG/check_pre_tag.py
      - git tag v$FARADAY_VERSION -m "$(cat CHANGELOG/$FARADAY_VERSION/community.md)"
      - git push --force github v$FARADAY_VERSION
      - scripts/github_release.py --deb-file ./faraday-server_amd64.deb --rpm-file ./faraday-server_amd64.rpm
    rules:
      - !reference [ .on-community-tag, rules ]
    dependencies:
      - generate_deb_master
      - generate_rpm_master
    tags:
      - faradaytests
